providers:
  - ## name is case insensitive (displaying it is sensitive). Must be unique.
    ## The name is also used as prefix in the user ID in the "user database".
    name: GitHub
    ## Identity providers (IdP)
    ## Supported: github, oidc
    type: github
    ## OAuth2 clientID
    clientID: 01234567890123456789
    ## OAuth2 secret
    clientSecret: 0123456789012345678901234567890123456789
  - name: OIDC
    type: oidc
    clientID: 01234567890123456789
    clientSecret: 0123456789012345678901234567890123456789
    ## Discovery endpoint.
    ## This points to "https://accounts.google.com/.well-known/openid-configuration
    endpoint: https://accounts.google.com
